[image]
# Merged customization hooks to run.
hooks_add =
  51-sn-collector.chroot

# OLPC Metrics Server
metrics_server_url = https://metrics.laptop.org/amp
activation_server_url = https://metrics.laptop.org/eas
